### ISSUE TITLE
main rating (in circle) vanishes after switching and interacting with a non-shop tab.

### ISSUE THREAD

**Issue by lindaicing** [CubeOfCheese/Ethicli#109]

**Comment by CubeOfCheese** [comment]
More testing of this bug has revealed the following:

There are two cases in which the display is incorrect.

The first occurs by following these steps:
1. Go to a shop page ex: adidas.com
2. Open a new non-shop page ex: wikipedia.org or refresh an existing non-shop page
3. Return to the adidas.com tab
Expected result: show 7.5 for adidas, not a shop for wikipedia, and then 7.5 again for adidas. 
Actual result: 7.5, not a shop, then nothing/10.

Second case:
1. Go to non-shop page ex: wikipedia.org
2. open or refresh a shop page ex: adidas.com
3. Return to wikipedia tab
Expected result: show not a shop, show 7.5, show not a shop
Actual result: show not a shop, show 7.5, show rating unavailable
