### ISSUE TITLE
Pitch Deck Create

### ISSUE THREAD

**Issue by lindaicing** [CubeOfCheese/Ethicli#113]

**Comment by CubeOfCheese** [comment]
Templates: https://slidebean.com/business-presentation-templates
And more templates: https://www.canva.com/templates/search/pitch-deck-presentations/

**Comment by CubeOfCheese** [comment]
![image](https://user-images.githubusercontent.com/16740469/85112802-1494e080-b1cb-11ea-881e-b981e5c48b60.png)

**Comment by lindaicing** [comment]
Top Pitch Deck Styles: https://docs.google.com/document/d/19XEVSNxr6YpOFkZ-6q2g-_2IAB_xnor5sNiQWk-VCAU/edit?usp=sharing

**Comment by CubeOfCheese** [comment]
https://docs.google.com/presentation/d/17wE4gOMCyY0O-j_PZ_1KE6cAkbH96265mm3nqlmCbv8/edit?usp=sharing
