### ISSUE TITLE
Expanded ratings tab visual development

### ISSUE THREAD

**Issue by lindaicing** [CubeOfCheese/Ethicli#146]

**Comment by lindaicing** [comment]
**Draft 1**
![draft](https://user-images.githubusercontent.com/38482675/86106011-e76eea80-ba74-11ea-9deb-0db731f14e8c.png)

**Version 1**
![MacBook Pro - 14](https://user-images.githubusercontent.com/38482675/86105908-c60dfe80-ba74-11ea-95b8-53f33cca3c11.png)

**Version 2**
![MacBook Pro - 12](https://user-images.githubusercontent.com/38482675/86105915-c73f2b80-ba74-11ea-82ac-87848cd4c03e.png)

**Comment by lindaicing** [comment]
Personally I like V1 better

**Comment by CubeOfCheese** [comment]
Version 2 feels more organized to me

**Comment by lindaicing** [comment]
Refined versions:
<img width="901" alt="Screen Shot 2020-06-30 at 10 58 33 AM" src="https://user-images.githubusercontent.com/38482675/86164599-e1095e80-bac6-11ea-8f5e-bc2ece6e8ce2.png">
