### ISSUE TITLE
Employee Gmail addresses

### ISSUE THREAD

**Issue by amtims** [CubeOfCheese/Ethicli#18]
Create multiple mail forwarding emails from Ethicli domain using [Google admin console ](https://support.google.com/a/answer/172171?hl=en)

**Comment by amtims** [comment]
@CubeOfCheese I'm only adding you here in case you want to verify the domain via Gmail on your end if it's simpler that way (it requires interaction with the domain somehow). Otherwise if I have the password I believe I can manage this!

**Comment by CubeOfCheese** [comment]
The link you shared is for G Suite which costs $6/month/user which is not accessible to us at the moment.

**Comment by CubeOfCheese** [comment]
Amy now has an email @ethicli.com

**Comment by amtims** [comment]
Oh my bad!! Yeah let’s avoid G Suite.

**Comment by CubeOfCheese** [comment]
The email forwarding only works one way so our personal email addresses would still be exposed as soon as we reply to an email. Closing issue because this isn't actually useful
