### ISSUE TITLE
Link pitch deck to "About" section on website

### ISSUE THREAD

**Issue by lindaicing** [CubeOfCheese/Ethicli#180]

**Comment by CubeOfCheese** [comment]
Oh this is smart. Wait! We should have a full page dedicated to possible investors maybe!?
It could talk about how Ethicli prioritizes ethical practices over profits. And also link to or have our pitch deck on the website

**Comment by lindaicing** [comment]
> Oh this is smart. Wait! We should have a full page dedicated to possible investors maybe!?
> It could talk about how Ethicli prioritizes ethical practices over profits. And also link to or have our pitch deck on the website

I think for now just linking it in the "about" section would be ok since we don't have investors yet. It would be good to prepare, but just adding it into the section is a quicker fix than making a full page for now. I'm thinking it would be good to have the new page after we have everything more set up in the extension (new tab, expanded stats, more solidified ratings, etc).

**Comment by CubeOfCheese** [comment]
You right you right. Just got excited 🪂

**Comment by lindaicing** [comment]
> You right you right. Just got excited 🪂

Definitely a good point for later!
