### ISSUE TITLE
Social Banners and Graphics Update

### ISSUE THREAD

**Issue by CubeOfCheese** [CubeOfCheese/Ethicli#181]
Update graphics that include the popup to show one where the barcharts are functional and bluesign/bcorp are not featured since we don't have rights to their names.

**Comment by lindaicing** [comment]
I accidentally added changes to the website graphics to the "Linked Pitchdeck" PR, so this issue will be for the physical graphics changes (for example the insta banners and promo materials)

**Comment by lindaicing** [comment]
- [ ] LinkedIn banner
- [ ] FB and Reddit
- [ ] Pitch Deck Graphics

**Comment by lindaicing** [comment]
Won't be able to update graphics for a while

**Comment by lindaicing** [comment]
- [ ] Finish all graphics
- [ ] Update socials
