### ISSUE TITLE
Display Company Name on Extension

### ISSUE THREAD

**Issue by lindaicing** [CubeOfCheese/Ethicli#182]

**Comment by lindaicing** [comment]
@CubeOfCheese 
The problem with this is that the URL of a site is only displayed if the page is a shopping page currently. This is so unnecessary message requests won't occur. 

Right now when users visit a non-shop page they won't be able to see the URL, and I'm not quite sure if there's a workaround for that (besides re-adding the sendmessage for every single popup page)

Showing the sitename
<img width="354" alt="Screen Shot 2020-07-17 at 12 16 52 AM" src="https://user-images.githubusercontent.com/38482675/87759238-d3402280-c7c2-11ea-9f9a-57a4e6e5d590.png">

When not on a shopping page
<img width="369" alt="Screen Shot 2020-07-17 at 12 17 41 AM" src="https://user-images.githubusercontent.com/38482675/87759296-f1a61e00-c7c2-11ea-993a-8448959fe64d.png">

**Comment by CubeOfCheese** [comment]
Well showing the company name is only useful when it is a shopping page. So you can just not include that in the non-shop html

**Comment by lindaicing** [comment]
> Well showing the company name is only useful when it is a shopping page. So you can just not include that in the non-shop html

Oh awesome! okiedoke
