### ISSUE TITLE
Dynamic More Details page

### ISSUE THREAD

**Issue by CubeOfCheese** [CubeOfCheese/Ethicli#209]
Depends on #208 
More Details page will need to utilize a template that is filled in with data from our company api call.

**Comment by lindaicing** [comment]
Visual "More Details" Tab
<img width="1267" alt="Screen Shot 2020-07-25 at 4 40 03 PM" src="https://user-images.githubusercontent.com/38482675/88468243-7ebd3700-ce95-11ea-8a6f-59896da44c5f.png">

<img width="1265" alt="Screen Shot 2020-07-25 at 4 40 18 PM" src="https://user-images.githubusercontent.com/38482675/88468247-87157200-ce95-11ea-9aa5-3146c6a581b7.png">
