### ISSUE TITLE
Design To-Do

### ISSUE THREAD

**Issue by lindaicing** [CubeOfCheese/Ethicli#22]
- Graphics/ Visuals
- Specific Mood
Keep developing for next week.

**Comment by lindaicing** [comment]
Developed some logo options: 
![Ethicli_Logos](https://user-images.githubusercontent.com/38482675/82962581-7455ee00-9f75-11ea-9e3e-f246b19a2b6c.png)

Some of the ones I like (with high contrast):
<img width="82" alt="Screen Shot 2020-05-26 at 5 22 36 PM" src="https://user-images.githubusercontent.com/38482675/82962639-a1a29c00-9f75-11ea-8d7c-ca2bc097f542.png">
<img width="81" alt="Screen Shot 2020-05-26 at 5 22 53 PM" src="https://user-images.githubusercontent.com/38482675/82962642-a36c5f80-9f75-11ea-983d-27ab3691355c.png">
<img width="85" alt="Screen Shot 2020-05-26 at 5 22 58 PM" src="https://user-images.githubusercontent.com/38482675/82962645-a6ffe680-9f75-11ea-8552-732aef94a58f.png">
<img width="90" alt="Screen Shot 2020-05-26 at 5 22 31 PM" src="https://user-images.githubusercontent.com/38482675/82962652-a8c9aa00-9f75-11ea-9794-282ddea98f83.png">

**Comment by lindaicing** [comment]
Created a moodboard for more visual styles: https://docs.google.com/document/d/1RW9RsXK0-RTTwleAJDY1wc82f6x0Wtdxzk09-8VOTlc/edit?usp=sharing
<img width="743" alt="Screen Shot 2020-05-26 at 5 29 15 PM" src="https://user-images.githubusercontent.com/38482675/82962920-6e144180-9f76-11ea-9780-4219b19be391.png">

Here's the first moodboard which has some nice styles: https://docs.google.com/document/d/1PSND2HUM5LCDGINp5NmSr9xuHPZC-DRddvsiP_zR7QM/edit?usp=sharing
<img width="764" alt="Screen Shot 2020-05-26 at 5 30 34 PM" src="https://user-images.githubusercontent.com/38482675/82963010-9e5be000-9f76-11ea-9bb6-3045c9cb8be2.png">
<img width="721" alt="Screen Shot 2020-05-26 at 5 31 12 PM" src="https://user-images.githubusercontent.com/38482675/82963035-b3d10a00-9f76-11ea-922d-7d06a8bbf6dd.png">
<img width="473" alt="Screen Shot 2020-05-26 at 5 31 35 PM" src="https://user-images.githubusercontent.com/38482675/82963060-c0edf900-9f76-11ea-9ee6-9ed0696b4211.png">

Please note that none of the images on these images are mine. They are pulled form online for inspiration!

**Comment by CubeOfCheese** [comment]
Shop ethicli or Buy ethicli?
Also Ethicli or ethicli?
I personally like lowercase

**Comment by CubeOfCheese** [comment]
The pot with a face stands out the most to me. It has a lot of character. As I started to type this I almost called it a pot head.
The circular e logos look very nice and official. Maybe a little too official to be our main logo?
The shopping cart with bar charts is probably my second favorite. Though I prefer the trapezoid shape over the rectangle shape.
This heart:
![Screen Shot 2020-05-28 at 5 10 06 PM](https://user-images.githubusercontent.com/16740469/83206608-19073580-a106-11ea-9d2d-cc1a926dcc69.png)
is one of my favorites as well.

I think it will be important to think about how small the icon has to be when deciding on a logo.

Do you think it would be beneficial to do ask some future users what they think about different logo designs?

**Comment by lindaicing** [comment]
It would be good to ask different potential users! I'm making more legit variations at the moment so each one looks more presentable/accurate.

**Comment by lindaicing** [comment]
> Shop ethicli or Buy ethicli?
> Also Ethicli or ethicli?
> I personally like lowercase

I also agree the lowercase looks better, more friendly. As for shop/ buy I think it would be good to get potential user feedback as well.
