### ISSUE TITLE
Design new badge format

### ISSUE THREAD

**Issue by lindaicing** [CubeOfCheese/Ethicli#234]

**Comment by lindaicing** [comment]
Preliminary drafts
<img width="858" alt="Screen Shot 2020-08-07 at 2 03 26 AM" src="https://user-images.githubusercontent.com/38482675/89629140-30734500-d852-11ea-9dac-51bfe6feb8f1.png">
<img width="578" alt="Screen Shot 2020-08-07 at 2 03 41 AM" src="https://user-images.githubusercontent.com/38482675/89629160-38cb8000-d852-11ea-8711-cdc4f11c355f.png">

Best out of the bunch:
<img width="382" alt="Screen Shot 2020-08-07 at 2 04 27 AM" src="https://user-images.githubusercontent.com/38482675/89629243-54cf2180-d852-11ea-95ce-d553ec171e10.png">

**Comment by CubeOfCheese** [comment]
I like frame 20
