### ISSUE TITLE
Create banner for Youtube channel

### ISSUE THREAD

**Issue by CubeOfCheese** [CubeOfCheese/Ethicli#274]
Minimum dimensions: 2048 x 1152

**Comment by lindaicing** [comment]
![YouTube](https://user-images.githubusercontent.com/38482675/92207870-df4d7580-ee3e-11ea-8d43-ae192ae94edc.png)
<img width="1309" alt="Screen Shot 2020-09-03 at 11 41 11 PM" src="https://user-images.githubusercontent.com/38482675/92207912-f55b3600-ee3e-11ea-9ee6-8d9f56931770.png">
