### ISSUE TITLE
Add to the FAQ for ethicli.com

### ISSUE THREAD

**Issue by amtims** [CubeOfCheese/Ethicli#278]

**Comment by CubeOfCheese** [comment]
The website already has a faq but it definitely needs to be updated. https://ethicli.com/faq

**Comment by amtims** [comment]
[Google Doc for FAQ](https://docs.google.com/document/d/144ieqO3VvK0s3LSJXvpwWup1GRpPcy38T18Yw1xPNG8/edit#heading=h.kvykoqmh60mo)
