### ISSUE TITLE
Recognize a shopping page

### ISSUE THREAD

**Issue by CubeOfCheese** [CubeOfCheese/Ethicli#3]

**Comment by CubeOfCheese** [comment]
browser action appears grayed out by default
![Screen Shot 2020-05-25 at 11 17 32 PM](https://user-images.githubusercontent.com/16740469/82866617-22ae5480-9ede-11ea-8592-eee1484fd50c.png)
When on a shopping page icon changes to color
![Screen Shot 2020-05-25 at 11 18 10 PM](https://user-images.githubusercontent.com/16740469/82866658-3659bb00-9ede-11ea-867d-2ae94421378c.png)

**Comment by lindaicing** [comment]
Is the Master updated? I can probably fix this and upload a temp logos as placeholders
