### ISSUE TITLE
Post to Social Media about new feature

### ISSUE THREAD

**Issue by CubeOfCheese** [CubeOfCheese/Ethicli#323]

**Comment by lindaicing** [comment]
https://drive.google.com/drive/u/0/folders/1FBF9jV1U27qAjqnaDwWKQFELmgaSwqNc

![GC-FB](https://user-images.githubusercontent.com/38482675/93969959-f25ab380-fd21-11ea-91f1-af8b7454d72a.png)
![GC-Insta](https://user-images.githubusercontent.com/38482675/93969974-f71f6780-fd21-11ea-958f-581e9dacb0aa.png)

![insta-productsuggest](https://user-images.githubusercontent.com/38482675/93969896-c9d2b980-fd21-11ea-96cc-bec3cdcb58c8.png)
![fb-productsuggest](https://user-images.githubusercontent.com/38482675/93969893-c6d7c900-fd21-11ea-8b57-69f913e7108a.png)

**Comment by amtims** [comment]
- [ ] Amy: IG

- [ ] Billy: Twitter, FB

- [ ] Linda: Linked in
