### ISSUE TITLE
Not all shopping pages are recognized

### ISSUE THREAD

**Issue by CubeOfCheese** [CubeOfCheese/Ethicli#34]
Need to improve shopping page recognition algorithm.
Examples of pages not recognized:
https://shop.nordstrom.com/
https://usa.jmkride.com/collections
https://www.fashionnova.com/
https://www.bestbuy.com/
https://www.target.com/

**Comment by lindaicing** [comment]
<img width="878" alt="Screen Shot 2020-05-29 at 1 40 31 PM" src="https://user-images.githubusercontent.com/38482675/83303565-1b26ce00-a1b2-11ea-8c1f-537d617d710f.png">


There seems to be lots of errors involving JQuery

**Comment by CubeOfCheese** [comment]
Since there are so many errors for various parts of things fundamental to jquery, my first guess is that jquery isn't being loaded as a dependency. Like the library isn't included. I don't know jquery so I can't help too much, but hopefully this is a good place to start

**Comment by lindaicing** [comment]
I think the font also isn't being loaded properly. We can probably keep them in for now and if we don't use them later on (meaning we don't write any code using jQuery) we can remove it.

**Comment by CubeOfCheese** [comment]
product-card
shopify-section
The second one especially should help recognize a lot more shopping pages

**Comment by lindaicing** [comment]
> product-card
> shopify-section
> The second one especially should help recognize a lot more shopping pages

Awesome! Adding to the array now

**Comment by CubeOfCheese** [comment]
Too broad and ongoing. More of a general goal than an issue/task
