### ISSUE TITLE
Reserve shop ethicli twitter handle

### ISSUE THREAD

**Issue by CubeOfCheese** [CubeOfCheese/Ethicli#36]
Currently we have @Buy_Ethicli but we decided Shop Ethicli sounds better.

**Comment by CubeOfCheese** [comment]
Did you also reserve the instagram already?

**Comment by amtims** [comment]
Yes, I have @shop.ethicli as our Instagram handle for now. It was @buy.ethicli before.

**Comment by CubeOfCheese** [comment]
Excellent. Thank you. Closing issue
