### ISSUE TITLE
Display data to user

### ISSUE THREAD

**Issue by CubeOfCheese** [CubeOfCheese/Ethicli#5]
Does not matter how it is displayed. This depends on #4.

**Comment by lindaicing** [comment]
Screenshot shows coded extension and placement.
Visuals not final but ID's are all tagged.

<img width="1281" alt="Screen Shot 2020-05-21 at 8 31 55 PM" src="https://user-images.githubusercontent.com/38482675/82628646-3be39800-9ba2-11ea-8938-7190f4e4753c.png">

**Comment by CubeOfCheese** [comment]
Depends on #4

**Comment by lindaicing** [comment]
Created visual part of extension (incomplete colors/branding) with code

<img width="973" alt="Screen Shot 2020-05-25 at 1 33 02 PM" src="https://user-images.githubusercontent.com/38482675/82841957-b5260800-9e8c-11ea-9260-9449356f2bfc.png">
