### ISSUE TITLE
Fix shops that have social media as their business pages which display as shops even though they are not (ex. LinkedIn)

### ISSUE THREAD

**Issue by lindaicing** [CubeOfCheese/Ethicli#58]

**Comment by CubeOfCheese** [comment]
![61293348240__65B57E52-8071-4073-A876-B33E239C8DA7](https://user-images.githubusercontent.com/16740469/83712451-b2d55380-a5da-11ea-855a-e463425310b1.jpeg)

**Comment by CubeOfCheese** [comment]
@cosmostevens Is this finished?
