### ISSUE TITLE
Sponsorship visual update

### ISSUE THREAD

**Issue by lindaicing** [CubeOfCheese/Ethicli#85]

**Comment by CubeOfCheese** [comment]
Can you add a brief description of what this issue is?

**Comment by lindaicing** [comment]
> Can you add a brief description of what this issue is?
This is the section where sponsors are to be displayed 
<img width="431" alt="Screen Shot 2020-07-02 at 11 47 36 AM" src="https://user-images.githubusercontent.com/38482675/86398050-d501d600-bc59-11ea-83e1-9136d6ba24de.png">

**Comment by lindaicing** [comment]
<img width="1440" alt="Screen Shot 2020-07-04 at 1 02 43 AM" src="https://user-images.githubusercontent.com/38482675/86508081-12697f00-bd92-11ea-8c38-4d0b72cc62c6.png">

On Hover
<img width="1440" alt="Screen Shot 2020-07-04 at 1 03 05 AM" src="https://user-images.githubusercontent.com/38482675/86508090-201f0480-bd92-11ea-934d-ea07518afc12.png">
