### ISSUE TITLE
Design/Branding

### ISSUE THREAD

**Issue by lindaicing** [CubeOfCheese/Ethicli#9]
Logo (Brainstorm for now)
Color Scheme 
Fonts/Typography

**Comment by lindaicing** [comment]
Figma File: https://www.figma.com/file/GoNMZmG99bxS941zP09tyV/EcoExtension?node-id=0%3A1
Moodboard Link: https://docs.google.com/document/d/1PSND2HUM5LCDGINp5NmSr9xuHPZC-DRddvsiP_zR7QM/edit?usp=sharing

![Page 9](https://user-images.githubusercontent.com/38482675/82524785-a930f380-9ae4-11ea-889e-87b1617f93df.png)
![Page 8](https://user-images.githubusercontent.com/38482675/82524791-ac2be400-9ae4-11ea-99cb-ad9cb806509d.png)

**Comment by CubeOfCheese** [comment]
Wow this is beautiful Linda, great work.

**Comment by lindaicing** [comment]
Finalized Color Scheme

<img width="635" alt="Screen Shot 2020-05-25 at 1 25 04 AM" src="https://user-images.githubusercontent.com/38482675/82793963-9725bc80-9e26-11ea-8819-6e37a2c07fce.png">

**Comment by lindaicing** [comment]
**Finalized Typeface**: Roboto

<img width="467" alt="Screen Shot 2020-05-25 at 1 46 24 AM" src="https://user-images.githubusercontent.com/38482675/82795917-8cb8f200-9e29-11ea-8332-4ea7e0c71f9c.png">

**Comment by CubeOfCheese** [comment]
Can this issue be closed?
